## DO NOT CHANGE WHILE INSTALLED! or -deinstall/-reinstall wont work correctly
## also unpredictable sideeffects to running Instance
## if var has #CHANGEABLEinPROD it can be changed ;)
general:
  client_type: "win" #one of managed_rhel, managed_win, rhel, win, ubuntu # this reflects the files got from the API!
  client_directory: "C:/Grafana-Alloy"
  rand_delay_executing_s: 600 # delay execution randomly between 0 to 600 seconds
  updater_client_name: "alloy_updater_client"
  build_type: "amd64_exe" #supported are amd64_exe, amd64_rpm #amd64deb is in the works
  rand_sleep_on_exe: "10m" #golang duration #CHANGEABLEinPROD
  sync_dirs: #DONOT CHANGE
    - config
    - scripts 
    - files
api:
  verify_ssl: false
  base_url: "http://127.0.0.1:8000/rdir/api" #CHANGEABLEinPROD
  #basic_auth: #CHANGEABLEinPROD
   # username: "supersave" #CHANGEABLEinPROD
    #password: "somestring" #CHANGEABLEinPROD

alloy:
  port: 10320
  interface_ip: "127.0.0.1"
  sysconfig_file: "/etc/sysconfig/alloy" #cant be changed
  service_name: "GrafanaAlloy" #cant be changed
  working_dir: "C:/Grafana-Appdata" #std cant be changed atm #unused
  max_bootup_duration: "5s" #used to check if app is serving #CHANGEABLEinPROD
  windows:
    exe_name: "alloy_amd64.exe"
    version_pattern: 'v?(\d+\.\d+\.\d+)'
    version_opt: "-v"


script_exporter:
  interface_ip: "127.0.0.1"
  port: 10321
  hardconfig_file: "C:/Grafana-Alloy/files/std_script_exporter_config.yaml"
  service_name: "ScriptExporter"
  max_bootup_duration: "5s" #used to check if app is serving
  windows:
    exe_name: "script_exporter_amd64.exe"
    version_pattern: 'v?(\d+\.\d+\.\d+)'
    version_opt: "-version"

windows:
  user: "LocalSystem"
  task: #if specified, creates task (windows) for continuos execution
    task_name: "AlloyUpdaterClient"
    task_intervall_in_m: 30 #in Minutes

shawl:
  windows:
    exe_name: "shawl_amd64.exe"
    version_pattern: 'v?(\d+\.\d+\.\d+)'
    version_opt: "-V"

logging: # This wont work, its hardcoded into the app
  log_file: "/var/log/alloy_updater_client.log"
  max_size: 5242880 # 5 MB in bytes
  backup_count: 4
  max_age_days: 30